### PR TITLE
make identifiers required

### PR DESCRIPTION
**Pull request by redmitry**
Any schema with no **required** properties would authenticate any arbitrary object.
To distinguish default schema objects from any other json objects; I suggest to make the identifiers mandatory.
For instance, 'VariantInSample' have two 'required' identifiers - 'variantId' and  'biosampleId'.
It is possible that more properties can be made mandatory.

### CODE REVIEW

**Comment by mbaudis** [comment]
@redmitry I don't think `variantId` is a required parameter since for primary observations frequently there won't be any "variant prototype" to relate to.

**Comment by redmitry** [comment]
> @redmitry I don't think `variantId` is a required parameter since for primary observations frequently there won't be any "variant prototype" to relate to.

@mbaudis Do you refer to the 'VariantInSample'?
"/biosamples/{id}/variants_in_sample"
"/g_variants/{id}/variants_in_sample"
"/analyses/{id}/variants_in_sample"
So, if I understand at least one of the IDs must be set? so we can set 
anyOf [{"required": "variantId"}, {"required": "biosampleId"},{"required": "analysisId"}]
The point that having no required properties makes any json object valid (i.g. "{}").

**Comment by mbaudis** [comment]
> "/biosamples/{id}/variants_in_sample"
"/g_variants/{id}/variants_in_sample"
"/analyses/{id}/variants_in_sample"

> So, if I understand at least one of the IDs must be set? so we can set
anyOf [{"required": "variantId"}, {"required": "biosampleId"},{"required": "analysisId"}]

Yes, that would work IMO. Though I would do only

```
anyOf:
  - required: "biosampleId"
  - required: "analysisId"
```

... which not only fulfills the formality but also is a logical requirement (variant instances have to be anchored to some provenance, so and/or biosample, analysis; whereas the canonical variant is on the other side of the object model).

@redmitry @sdelatorrep ?

**Comment by sdelatorrep** [comment]
Please, @redmitry, change the base branch to `develop`. Thanks!
I've also just noticed that PR #26 was still pending to be merged: apart from updating the content, this PR also included some required fields for each of the entities.

**Comment by sdelatorrep** [comment]
If you don't mind, I think we should close this PR as #26 is more complete (it adds fixes, new fields, etc.), and also adds mandatory properties.

**Comment by redmitry** [comment]
I would close this PR without merge.

**Pull request closed without merging**
